name: Deploy:development

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    types: [opened, reopened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
     
      - run: npm i --global vercel@latest
      - run: vercel pull --yes --environment=preview --token=${{ secrets.vercel_token }}
        env:
          VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
          VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}

      - run: vercel build --token=${{ secrets.vercel_token }}
        env:
          VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
          VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}

      - run: vercel deploy --prebuilt --token=${{ secrets.vercel_token }}
        env:
          VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
          VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}