name: Deploy:production

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./app
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
     
      - run: npm i --global vercel@latest
      - run: vercel pull --yes --environment=production --token=${{ secrets.vercel_token }}
        env:
          VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
          VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}

      - run: vercel build --token=${{ secrets.vercel_token }}
        env:
          VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
          VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}

      - run: vercel deploy --token=${{ secrets.vercel_token }}
        env:
          VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
          VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}